---
title: 'Bitácora de trabajo: recuperación de lecturas no humanas desde BAM WGS'
author: "Ariadna Badia"
date: "2026-06-04"
output:
  pdf_document: default
  html_document: default
---

# Bitácora de trabajo: recuperación de lecturas no humanas desde BAM WGS

## Día 1 — Exploración inicial y decisiones metodológicas

### Objetivo del día

Explorar los archivos disponibles de WGS de melanoma acral.

### Punto de partida

Me dí cuenta que los datos disponibles no son FASTQ crudos, son archivos BAM ya alineados al genoma humano de referencia GRCh38 + decoy + HLA y están en la ruta:

``` bash
/mnt/data/drobles/backup/acral_mexican_wgs/
```

Inicialmente pensé que, al estar los BAMs alineados a humano, las lecturas microbianas podrían haberse perdido. Sin embargo, entendí que un BAM puede conservar lecturas que no mapearon a humano. Estas lecturas quedan marcadas con el flag `4` y pueden verse con `samtools`.

Ejemplo piloto, estando en:

``` bash
/mnt/data/sur/users/abadia/microbiome_acral_test/
```

Cargo:

``` bash
module load samtools/1.22.1
```

Tomo una muestra y aplico:

``` bash
samtools view -b -f 4 /mnt/data/drobles/backup/acral_mexican_wgs/3165_PD60843a/mapped_sample/HUMAN_GRCh38_full_analysis_set_plus_decoy_hla_genomic_PD60843a.dupmarked.bam
```

Para saber cuántas lecturas hay:

``` bash
samtools view -c PD60843a_unmapped.bam
```

Resultado: 1,895,260 reads

De las reads totales.

Que vi con:

``` bash
samtools view -c /mnt/data/drobles/backup/acral_mexican_wgs/3165_PD60843a/mapped_sample/HUMAN_GRCh38_full_analysis_set_plus_decoy_hla_genomic_PD60843a.dupmarked.bam
```

## Día 2 — Extracción de reads no mapeadas y generación de FASTQ piloto

Para observar a qué microbios pertenecen esas reads, primero necesito preparar las lecturas para el clasificador. La mayoría de las herramientas de microbioma esperan como entrada FASTQ.

### Objetivo del día

Extraer las lecturas no mapeadas de la muestra `PD60843a` y convertirlas a FASTQ.

### Directorio de trabajo

``` bash
/mnt/data/sur/users/abadia/microbiome_acral_test/
```

### Extracción de reads no mapeadas

La extracción se hizo con un job.

``` bash
nano extract_unmapped.sh
```

Dentro del script:

``` bash
#!/bin/bash
#SBATCH --job-name=extract_unmapped
#SBATCH --cpus-per-task=4
#SBATCH --mem=16G
#SBATCH --output=slurm-%j.out

module load samtools/1.22.1

samtools view -b -f 4 \
/mnt/data/drobles/backup/acral_mexican_wgs/3165_PD60843a/mapped_sample/HUMAN_GRCh38_full_analysis_set_plus_decoy_hla_genomic_PD60843a.dupmarked.bam \
> /mnt/data/sur/users/abadia/microbiome_acral_test/PD60843a_unmapped.bam
```

Doy permisos:

``` bash
chmod +x extract_unmapped.sh
```

El job se mandó con:

``` bash
sbatch extract_unmapped.sh
```

Job ID:

``` bash
204219
```

Para ver si seguía corriendo, monitoreaba con:

``` bash
squeue -j 204219
```

Archivo generado:

``` bash
PD60843a_unmapped.bam
```

Ruta:

``` bash
/mnt/data/sur/users/abadia/microbiome_acral_test/PD60843a_unmapped.bam
```

Verificación:

``` bash
samtools quickcheck PD60843a_unmapped.bam
echo $?
```

Resultado:

``` bash
0
```

Sgnifica que el BAM generado estaba correcto.

Conteo de lecturas:

``` bash
samtools view -c PD60843a_unmapped.bam
```

Resultado:

``` bash
1895260
```

Se recuperaron 1,895,260 lecturas no mapeadas a humano.

### Conversión de BAM no mapeado a FASTQ

El archivo `PD60843a_unmapped.bam` se convirtió a FASTQ con:

``` bash
samtools fastq PD60843a_unmapped.bam > PD60843a_unmapped.fastq
```

Archivos generados:

``` bash
PD60843a_unmapped.bam
PD60843a_unmapped.fastq
```

Tamaño del FASTQ:

``` bash
ls -lh PD60843a_unmapped.fastq
```

Resultado:

``` bash
630M
```

Número de líneas:

``` bash
wc -l PD60843a_unmapped.fastq
```

Resultado:

``` bash
7581040
```

Como cada read en FASTQ ocupa 4 líneas:

``` bash
7581040 / 4 = 1895260 reads
```

Esto coincide con el conteo del BAM no mapeado.

### Instalar Kraken ¿o ya está instalado?

Ahora necesito la herramienta de clasificación taxonómica, consideré utilizar Kraken2, por que es muy utilizado y clasifica rápido.

Antes de intentar instalar Kraken2, revisé si ya estaba disponible como módulo del sistema:

``` bash
module avail kraken
```

Resultado:

``` bash
kraken/2.1.3
kraken/2.1.6 (D)
```

O sea ya esta instalado en el cluster, por lo que no es necesario realizar una instalación local.

Posteriormente cargué el módulo:

``` bash
module load kraken/2.1.6
```

y confirmé que Kraken2 estaba disponible ejecutando:

``` bash
kraken2 --help
```

La herramienta requiere también de una base de datos taxonómica para poder clasificar lecturas. Por lo que intenté localizar una base de datos ya existente dentro del cluster buscando archivos que pudieran estar en una base para Kraken2:

``` bash
find /mnt/data -type f -name "hash.k2d" 2>/dev/null
```

También busqué directorios relacionados con Kraken:

``` bash
find /mnt/data -type d -iname "*kraken*" 2>/dev/null
```

Después de varias búsquedas extensas no encontré ninguna base de datos Kraken utilizable para el análisis.

### Construcción de la base de datos Kraken

Primero creé un directorio para almacenar la base:

``` bash
mkdir -p /mnt/data/sur/users/abadia/kraken_db
```

Posteriormente elaboré un script para mandar job:

``` bash
nano build_kraken_standard.sh
```

Con esto dentro:

``` bash
#!/bin/bash
#SBATCH --job-name=build_kraken_db
#SBATCH --cpus-per-task=16
#SBATCH --mem=128G
#SBATCH --time=2-00:00:00
#SBATCH --output=build_kraken_%j.out
#SBATCH --error=build_kraken_%j.err

module load kraken/2.1.6

DB=/mnt/data/sur/users/abadia/kraken_db/standard
mkdir -p $DB

kraken2-build --standard --threads 16 --db $DB
```

y lo mandé:

``` bash
sbatch build_kraken_standard.sh
```

Slurm asignó:

``` bash
Job ID: 207013
```

### Conversión de BAM completo a FASTQ pareado

Después pensé que una limitación era que si una lectura microbiana mapea parcialmente a humano o tiene baja calidad de mapeo, podría no aparecer como `unmapped`. Por eso, extraer solo reads con flag `4` es una primera aproximación, pero no necesariamente recupera toda la señal microbiana posible.

Si tuviera los datos crudos(FASTQ) podría aplicar los filtros de alineamiento que yo considere necestarios.

Se supone que los BAM deberían contener las lecturas originales + la información de alineamiento; y en en teoría al convertir de BAM a FASTQ debería encontrar lo mismo que en un FASTQ original. Para ver si mi teoría es cierta lo voy a convertir:

Lo mandé en job:

``` bash
nano bam_to_fastq_PD60843a.sh
```

script:

``` bash
#!/bin/bash
#SBATCH --job-name=bam2fq_PD60843a
#SBATCH --cpus-per-task=8
#SBATCH --mem=32G
#SBATCH --time=24:00:00
#SBATCH --output=bam2fq_%j.out
#SBATCH --error=bam2fq_%j.err

module load samtools/1.22.1

BAM=/mnt/data/drobles/backup/acral_mexican_wgs/3165_PD60843a/mapped_sample/HUMAN_GRCh38_full_analysis_set_plus_decoy_hla_genomic_PD60843a.dupmarked.bam

samtools fastq \
  -1 /mnt/data/sur/users/abadia/PD60843a_R1.fastq \
  -2 /mnt/data/sur/users/abadia/PD60843a_R2.fastq \
  -0 /dev/null \
  -s /dev/null \
  $BAM
```

### Revisar flagstat y stats

Pensando bien, todavía no entiendo bien qué contiene el BAM. Necesito saber el número total de lecturas, porcentaje de alineamiento, duplicados, longitud de lectura y otras métricas de calidad:

``` bash
nano qc_bam_PD60843a.sh
chmod +x qc_bam_PD60843a.sh
sbatch qc_bam_PD60843a.sh
```

Script:

``` bash
#!/bin/bash
#SBATCH --job-name=qc_PD60843a
#SBATCH --cpus-per-task=4
#SBATCH --mem=16G
#SBATCH --output=qc_PD60843a_%j.out
#SBATCH --error=qc_PD60843a_%j.err

module load samtools/1.22.1

BAM=/mnt/data/drobles/backup/acral_mexican_wgs/3165_PD60843a/mapped_sample/HUMAN_GRCh38_full_analysis_set_plus_decoy_hla_genomic_PD60843a.dupmarked.bam

samtools flagstat $BAM > /mnt/data/sur/users/abadia/microbiome_acral_test/PD60843a.flagstat

samtools stats $BAM > /mnt/data/sur/users/abadia/microbiome_acral_test/PD60843a.stats
```
Mañana revisaré el output de los jobs. 